[package]
name = "free-surface"
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"

[[bin]]
name = "check-config"

[[bin]]
name = "slf-dump"
path = "src/bin/slf_dump.rs"

[dependencies]
anstream = "1.0.0"
anstyle = "1.0.0"
anyhow = "1"
binrw     = "0.15"
chrono = "0.4"
clap = { version = "4.6.1", features = ["derive"] }
fluent-bundle = "0.16"
fluent-i18n = "0.1.0"
fluent-langneg = "0.13"
num-traits = "0.2.19"
regex = "1.12.3"
serde = "1.0.228"
serde_json = "1.0"
sys-locale = "0.3"
unic-langid = "0.9"
thiserror = "2.0.18"

fluent-message = {
    git = "https://github.com/beg0/fluent-message.git",
    rev = "a45621208c28e308980de7bce99a0bdfc3cc4886",
    features=["i18n"]
}
nalgebra = { version="0.35.0", features = ["bytemuck"]}

[dev-dependencies]
assert_cmd = "2"
indoc = "2.0.7"
flate2 = "1"
fs4 = "1.1.0"
glob = "0.3"
serde_json_path = "0.7.2"
sha2 = "0.10"
tar = "0.4"
tempfile = "3"
predicates = { version = "3", features = ["diff", "color"] }
ureq = "3"
